title: "vinash"
email: avinashhhsinghhh@gmail.com
description: "My Journey to Red Team Operator, Learning Progress, CTF writeups, red teaming notes"
baseurl: ""
url: ""
twitter_username:
github_username: 97-vinash

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

header_title: "VINASH"

permalink: /:year/:month/:day/:title/

plugins:
  - jekyll-feed
  - jekyll-seo-tag

exclude:
  - node_modules
  - vendor
  - .git
  - .sass-cache
  - Gemfile
  - Gemfile.lock
  - README.md